### ISSUE TITLE
Add "update available" in the tree view

### ISSUE THREAD

**Issue by SrBrahma** [DennisvHest/vscode-npm-browser#20]
Would be really good if there was a quick way to see if there are updates for the dependecies (and dev-deps) without having to open them one by one. As it can be time consuming to fetch the data from all packages, there could be a button for it in the tree view header, and maybe the tree item icon could change if there is an available update, maybe even with a icon for patch / minor / major available updates.

**Comment by DennisvHest** [comment]
Hey @SrBrahma, thanks for creating this issue. I had a similar feature in mind aswell, but what kept me from implementing this is that the NPM registry api is rate limited (even tough the limit is very big) and it is not possible to fetch multiple packages (by name) in one request.

This might not be a problem anymore if packages are fetched with running the `npm view` command instead of fetching them from the api like this PR suggests: #23 

I will look into this when I have time to work on this in early october.

**Comment by DennisvHest** [comment]
Hi @SrBrahma, this feature has been added in release [1.1.0](https://github.com/DennisvHest/vscode-npm-browser/releases/tag/1.1.0). I will close this issue.

**Comment by SrBrahma** [comment]
Does the update all also updates major versions?

**Comment by DennisvHest** [comment]
Update all basically just runs `npm update`, so it will update packages based on what is configured in the package.json. If you have a package installed with version >=1.0.0 and there is a 2.0.0 version, it will update to 2.0.0.

**Comment by DennisvHest** [comment]
Maybe in a later update I will add an option to show updates independent of what is configured in the package.json, so it will show major updates even if only minor updates are configured.
