### ISSUE TITLE
Issue with private NPM packages. 

### ISSUE THREAD

**Issue by samdesota** [DennisvHest/vscode-npm-browser#22]
It seems like private npm packages with custom registries like the GitHub package repo cannot be accessed with this tool. It's useful to be able to select a new version of private packages since these change super frequently within an organization.

I'll create a PR to fix if you can point me in the right direction.

**Comment by DennisvHest** [comment]
Hey @samdesota, thanks for creating this issue and thanks for the PR. It would indeed be nice to fetch all package info with `npm view` instead of fetching it from the NPM registry api. I didn't actually know this was possible :). I also see that searching packages is possible via `npm search`, so it might just be possible to not have to fetch anything from the registry api at all. This would be nice because right now I have to maintain a CORS proxy and there is rate limiting on the api (though the limit is very big).

Sadly I don't really have the time right now to work on this, so this will have to wait until early october when I have more time to work on this.

**Comment by DennisvHest** [comment]
Hey @samdesota, partial support for private packages has been added in the [1.0.4](https://github.com/DennisvHest/vscode-npm-browser/releases/tag/1.0.4) release. Thanks for the help with the pull request.

As a next feature it would be nice if private packages would show up in the search. This is a little more complex than I thought, because the `npm search` cli command is lacking some things, but something might be possible so I will create an issue and maybe look into it.
