### ISSUE TITLE
Not showing update available like it used to

### ISSUE THREAD

**Issue by MuTsunTsai** [DennisvHest/vscode-npm-browser#34]
Just noticed that update notification somehow cease to work. At first I wonder if this is a v1.1.2 thing, but downgrading doesn't solve the issue either. I'm really confused as this didn't happen before.

![image](https://user-images.githubusercontent.com/39870664/152681975-811177d0-5931-4910-8b22-e3081ddec4be.png)

Take TypeScript for example, the installed version for this project is 4.5.4, and it should show me on the left that 4.5.5 is available.

**Comment by DennisvHest** [comment]
Hey @MuTsunTsai, I have cloned your box-pleating-studio repo and can reproduce the problem.

It is weird because under the hood the extension executes `npm outdated` and then compares the 'Current' and 'Wanted' versions. If I do this manually, I get the following:

![image](https://user-images.githubusercontent.com/18610083/152685000-1c506317-451a-45dc-acb6-3907a2c4a1c2.png)

As you can see, many updates are not showing up and if they do show up, the 'Current' and 'Wanted' versions match.

What is even weirder, is that if I reinstall typescript to the same version in your package.json, the update for typescript does show up in `npm outdated` and therefore also in the dependencies list.

This looks to possibly be an issue with the npm itself.
