### ISSUE TITLE
Loading package info is very slow

### ISSUE THREAD

**Issue by MuTsunTsai** [DennisvHest/vscode-npm-browser#38]
One thing that kinda bothers me with this extension is that it takes almost 10 seconds from selecting a package to fully show its info in the webview. And no, I don't have a slow internet. If I directly go to the NPM website it shows me the same content (and more) in about 1 second.

I'm not sure if this is the main cause to the problem, but upon inspecting the source code I notice that you're using a herokuapp proxy to fetch data from registry.npmjs.com, apparently as a workaround for the CORS issue with the webview. However fetching this way is surely slower. My understanding is that we have a CORS issue here because we're fetching data inside a webview. What if we fetch the data in the extension instead and pass the data to the webview? Just a thought.

**Comment by DennisvHest** [comment]
Hi @MuTsunTsai, thanks for the suggestion!

I have created a new release ([1.1.4](https://github.com/DennisvHest/vscode-npm-browser/releases/tag/1.1.4)) that removes the calls to the CORS proxy and fetches the data from the extension itself. I needed to to this eventually anyway, because Heroku is removing their free application plans, so my proxy server is going offline 😅.

This improves the performance, but I think the main culprit of the slow loading was an unnecessary check for package updates every time a dependency was selected from the dependency list. This blocked the loading of the package data, so I removed this unnecessary check.
